/// <reference path="../.astro/types.d.ts" />

// Vite raw imports
declare module '*.sql?raw' {
  const content: string;
  export default content;
}

// Cloudflare Workers environment bindings
// In Astro 6 + @astrojs/cloudflare v13, bindings are accessed via
// `import { env } from 'cloudflare:workers'` instead of `locals.runtime.env`
interface D1PreparedStatement {
  bind(...values: unknown[]): D1PreparedStatement;
  first<T = unknown>(): Promise<T | null>;
  all<T = unknown>(): Promise<{ results: T[] }>;
  run<T = unknown>(): Promise<T>;
}

interface D1Database {
  prepare(query: string): D1PreparedStatement;
  batch<T = unknown>(statements: D1PreparedStatement[]): Promise<T[]>;
  withSession?(constraint?: 'first-unconstrained' | 'first-primary' | string): D1Database;
}

interface R2HTTPMetadata {
  contentType?: string;
  contentDisposition?: string;
}

interface R2ObjectBody {
  key?: string;
  size?: number;
  etag?: string;
  body: ReadableStream;
  httpEtag: string;
  uploaded?: Date;
  httpMetadata?: R2HTTPMetadata;
}

interface R2Object {
  key: string;
  size: number;
  etag: string;
  httpEtag: string;
  uploaded: Date;
  httpMetadata?: R2HTTPMetadata;
}

interface R2Objects {
  objects: R2Object[];
  delimitedPrefixes: string[];
  truncated: boolean;
  cursor?: string;
}

interface R2Bucket {
  put(
    key: string,
    value: ArrayBuffer | ReadableStream | string | Blob,
    options?: { httpMetadata?: R2HTTPMetadata },
  ): Promise<unknown>;
  get(key: string): Promise<R2ObjectBody | null>;
  head(key: string): Promise<R2Object | null>;
  list(options?: {
    prefix?: string;
    delimiter?: string;
    limit?: number;
    cursor?: string;
  }): Promise<R2Objects>;
  delete(key: string): Promise<void>;
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

interface CacheStorage {
  readonly default: Cache;
}

interface CloudflareEnv {
  DB: D1Database;
  BUCKET: R2Bucket;
  [key: string]: unknown;
}

// Module declaration for cloudflare:workers env typing
declare module 'cloudflare:workers' {
  const env: CloudflareEnv;
  export { env };
}

// Virtual module: plugin registry (generated by plugin-loader integration and
// statically imported by middleware.ts so plugin loaders are registered before
// the first request of a cold isolate)
declare module 'virtual:typecho-plugin-registry';

// Virtual module: theme template components (generated by theme-loader integration)
declare module 'virtual:theme-templates' {
  import type { ThemeTemplateMap } from '@/lib/theme-props';
  export const themeTemplates: Record<string, Partial<ThemeTemplateMap>>;
}

declare namespace App {
  interface Locals {
    // Execution context (replaces locals.runtime.ctx)
    cfContext?: ExecutionContext;
    /**
     * Pagination page number extracted from `/page/N/` URL suffixes by
     * middleware.ts. Read by page-data prepareArchive* functions.
     */
    _page?: number;
    /** Astro Cloudflare adapter attaches this at runtime. */
    runtime?: {
      ctx?: { waitUntil?(promise: Promise<unknown>): void };
      env?: CloudflareEnv;
    };
  }
}
