/// <reference path="../.astro/types.d.ts" />

// Vite raw imports
declare module '*.sql?raw' {
  const content: string;
  export default content;
}

// Worker runtime and binding declarations are generated at the repository root
// by `pnpm run types:workers`. Keep only application-owned declarations here.

// Astro's DOM library contributes CacheStorage without the Workers-only
// `default` cache. Merge that platform extension back into the generated type.
interface CacheStorage {
  readonly default: Cache;
}

// Virtual module: plugin registry (generated by plugin-loader integration and
// statically imported by middleware.ts so plugin loaders are registered before
// the first request of a cold isolate)
declare module 'virtual:typecho-plugin-registry';

// Virtual module: theme template components (generated by theme-loader integration)
declare module 'virtual:theme-templates' {
  import type { ThemeTemplateMap } from '@/lib/theme-props';
  export const themeTemplates: Record<string, Partial<ThemeTemplateMap>>;
}

declare namespace App {
  interface Locals {
    // Execution context (replaces locals.runtime.ctx)
    cfContext?: ExecutionContext;
    /**
     * Pagination page number extracted from `/page/N/` URL suffixes by
     * middleware.ts. Read by page-data prepareArchive* functions.
     */
    _page?: number;
    /** Astro Cloudflare adapter attaches this at runtime. */
    runtime?: {
      ctx?: { waitUntil?(promise: Promise<unknown>): void };
      env?: Cloudflare.Env;
    };
  }
}
